-- Create Tables for Utility per Select

-- CMD_OUTPUT  -- Command Output, e.g. Display
-- CMD_PROT    -- Protocol Usage SP for Commands
-- PROCPROT    -- Protocol Usage SP for Utility
-- UTILPRINT   -- Utility Output, e.g. Reorg



--
     CREATE DATABASE
       DBIDUG
         BUFFERPOOL BP2
         INDEXBP BP1
         CCSID EBCDIC
     ;
-- GRANT DBADM ON DATABASE DBIDUG TO PROD;

     CREATE
      TABLESPACE TSIDUG01
         IN DBIDUG
         USING STOGROUP GT01
         PRIQTY -1
         SECQTY -1
         ERASE NO
         FREEPAGE 0
         PCTFREE 0 FOR UPDATE -1
         GBPCACHE CHANGED
         COMPRESS NO
         TRACKMOD NO
         LOGGED
         DSSIZE 64 G
         SEGSIZE 64
         MAXPARTITIONS 2
         BUFFERPOOL BP2
         LOCKSIZE ANY
         LOCKMAX SYSTEM
         CLOSE YES
         CCSID EBCDIC
         MAXROWS 255
     ;

     CREATE TABLE
       IDUG.PROCPROT
        (
        LFDNR   INTEGER NOT NULL
         GENERATED ALWAYS
         AS IDENTITY
         (
           START WITH 1
           INCREMENT BY 1
           MINVALUE 1
           MAXVALUE 2147483647
           NO CYCLE
           CACHE 20
           NO ORDER
         )
       ,ROW_CHANGE_SYS   TIMESTAMP NOT NULL
         GENERATED ALWAYS
         FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP
       ,CLIENT_ACCTNG   VARCHAR(255) GENERATED ALWAYS AS (CURRENT CLIENT_ACCTNG)
         FOR SBCS DATA
       ,CLIENT_APPLNAME   VARCHAR(255) GENERATED ALWAYS AS (CURRENT CLIENT_APPLNAME)
         FOR SBCS DATA
       ,CLIENT_CORR_TOKEN   VARCHAR(255) GENERATED ALWAYS AS (CURRENT CLIENT_CORR_TOKEN)
         FOR SBCS DATA
       ,CLIENT_USERID   VARCHAR(255) GENERATED ALWAYS AS (CURRENT CLIENT_USERID)
         FOR SBCS DATA
       ,CLIENT_WRKSTNNAME   VARCHAR(255) GENERATED ALWAYS AS (CURRENT CLIENT_WRKSTNNAME)
         FOR SBCS DATA
       ,SERVER   CHAR(16) GENERATED ALWAYS AS (CURRENT SERVER)
         FOR SBCS DATA
       ,SQLID   VARCHAR(16) GENERATED ALWAYS AS (CURRENT SQLID)
         FOR SBCS DATA
       ,"SESSION_USER"   VARCHAR(128) GENERATED ALWAYS AS (SESSION_USER)
         FOR SBCS DATA
       ,DBNAME   CHAR(8) NOT NULL
         FOR SBCS DATA
       ,TSNAME   CHAR(8) NOT NULL
         FOR SBCS DATA
       ,PROCNAME   CHAR(20) NOT NULL
         FOR SBCS DATA
       ,RETCODE   INTEGER NOT NULL WITH DEFAULT -1
        )
         IN DBIDUG.TSIDUG01
         CCSID EBCDIC
         NOT VOLATILE
         APPEND NO
         NO KEY LABEL
     ;

GRANT INSERT, SELECT ON TABLE IDUG.PROCPROT TO PUBLIC;
     CREATE
      TABLESPACE TSIDUG02
         IN DBIDUG
         USING STOGROUP GT01
         PRIQTY -1
         SECQTY -1
         ERASE NO
         FREEPAGE 0
         PCTFREE 0 FOR UPDATE -1
         GBPCACHE CHANGED
         COMPRESS NO
         TRACKMOD NO
         LOGGED
         DSSIZE 64 G
         SEGSIZE 64
         MAXPARTITIONS 2
         BUFFERPOOL BP2
         LOCKSIZE ANY
         LOCKMAX SYSTEM
         CLOSE YES
         CCSID EBCDIC
         MAXROWS 255
     ;

     CREATE TABLE
       IDUG.UTILPRINT
        (
        LFDNR   INTEGER NOT NULL
       ,SEQNO   INTEGER NOT NULL
       ,TEXT   VARCHAR(254)
         FOR SBCS DATA
       ,ROW_CHANGE_SYS   TIMESTAMP NOT NULL
         GENERATED ALWAYS
         FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP
        )
         IN DBIDUG.TSIDUG02
         CCSID EBCDIC
         NOT VOLATILE
         APPEND NO
         NO KEY LABEL
     ;

GRANT INSERT, SELECT ON TABLE IDUG.UTILPRINT TO PUBLIC;
     CREATE
      TABLESPACE TSIDUG03
         IN DBIDUG
         USING STOGROUP GT01
         PRIQTY -1
         SECQTY -1
         ERASE NO
         FREEPAGE 0
         PCTFREE 0 FOR UPDATE -1
         GBPCACHE CHANGED
         COMPRESS NO
         TRACKMOD NO
         LOGGED
         DSSIZE 64 G
         SEGSIZE 64
         MAXPARTITIONS 2
         BUFFERPOOL BP2
         LOCKSIZE ANY
         LOCKMAX SYSTEM
         CLOSE YES
         CCSID EBCDIC
         MAXROWS 255
     ;
     CREATE TABLE
       IDUG.CMD_OUTPUT
        (
        LFDNR   INTEGER NOT NULL
       ,SEQNO   INTEGER NOT NULL
       ,TEXT   CHAR(80)
         FOR SBCS DATA
       ,ROW_CHANGE_SYS   TIMESTAMP NOT NULL
         GENERATED ALWAYS
         FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP
        )
         IN DBIDUG.TSIDUG03
         CCSID EBCDIC
         NOT VOLATILE
         APPEND NO
         NO KEY LABEL
     ;
 GRANT INSERT, SELECT ON TABLE IDUG.CMD_OUTPUT TO PUBLIC;
     CREATE
      TABLESPACE TSIDUG04
         IN DBIDUG
         USING STOGROUP GT01
         PRIQTY -1
         SECQTY -1
         ERASE NO
         FREEPAGE 0
         PCTFREE 0 FOR UPDATE -1
         GBPCACHE CHANGED
         COMPRESS NO
         TRACKMOD NO
         LOGGED
         DSSIZE 64 G
         SEGSIZE 64
         MAXPARTITIONS 2
         BUFFERPOOL BP2
         LOCKSIZE ANY
         LOCKMAX SYSTEM
         CLOSE YES
         CCSID EBCDIC
         MAXROWS 255
     ;
     CREATE TABLE
       IDUG.CMD_PROT
        (
        LFDNR   INTEGER NOT NULL
         GENERATED ALWAYS
         AS IDENTITY
         (
           START WITH 1
           INCREMENT BY 1
           MINVALUE 1
           MAXVALUE 2147483647
           NO CYCLE
           CACHE 20
           NO ORDER
         )
       ,ROW_CHANGE_SYS   TIMESTAMP NOT NULL
         GENERATED ALWAYS
         FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP
       ,CLIENT_ACCTNG   VARCHAR(255) GENERATED ALWAYS AS (CURRENT CLIENT_ACCTNG)
         FOR SBCS DATA
       ,CLIENT_APPLNAME   VARCHAR(255) GENERATED ALWAYS AS (CURRENT CLIENT_APPLNAME)
         FOR SBCS DATA
       ,CLIENT_CORR_TOKEN   VARCHAR(255) GENERATED ALWAYS AS (CURRENT CLIENT_CORR_TOKEN)
         FOR SBCS DATA
       ,CLIENT_USERID   VARCHAR(255) GENERATED ALWAYS AS (CURRENT CLIENT_USERID)
         FOR SBCS DATA
       ,CLIENT_WRKSTNNAME   VARCHAR(255) GENERATED ALWAYS AS (CURRENT CLIENT_WRKSTNNAME)
         FOR SBCS DATA
       ,SERVER   CHAR(16) GENERATED ALWAYS AS (CURRENT SERVER)
         FOR SBCS DATA
       ,SQLID   VARCHAR(16) GENERATED ALWAYS AS (CURRENT SQLID)
         FOR SBCS DATA
       ,"SESSION_USER"   VARCHAR(128) GENERATED ALWAYS AS (SESSION_USER)
         FOR SBCS DATA
       ,CMD   VARCHAR(128) NOT NULL
         FOR SBCS DATA
       ,RETCODE   INTEGER NOT NULL WITH DEFAULT -1
        )
         IN DBIDUG.TSIDUG04
         CCSID EBCDIC
         NOT VOLATILE
         APPEND NO
         NO KEY LABEL
     ;
 GRANT INSERT, SELECT ON TABLE IDUG.CMD_PROT TO PUBLIC;
